# Data analysis using Numpy

   Numpy is an open source python lib. used for working with Array 
       
   It stands for numarical python

In [1]:
import numpy as np

In [2]:
x=np.array([1,2,3,4,5])
print(x)

[1 2 3 4 5]


In [3]:
type(x)

numpy.ndarray

In [4]:
x.shape

(5,)

In [6]:
x.ndim

1

In [9]:
y=np.array([[1,2,3,4,5],[1,3,4,5,7]])
print(y)

[[1 2 3 4 5]
 [1 3 4 5 7]]


In [10]:
type(y)

numpy.ndarray

In [11]:
y.shape

(2, 5)

In [13]:
y.ndim

2

In [18]:
z=np.array([[1,2,3,4,5],[1,3,4,5,9]])
print(z)

[[1 2 3 4 5]
 [1 3 4 5 9]]


In [19]:
type(z)

numpy.ndarray

In [20]:
z.shape

(2, 5)

In [23]:
z.ndim

2

In [26]:
z[1][2]

4

In [40]:
a=np.array([[[1,8,3,10,15],[1,13,4,50,9],[4,25,6,7,18]]])
print(a)

[[[ 1  8  3 10 15]
  [ 1 13  4 50  9]
  [ 4 25  6  7 18]]]


In [41]:
a.shape

(1, 3, 5)

In [42]:
a.ndim

3

In [43]:
a[0][1][4]

9

In [44]:
np.amax(a)

50

In [45]:
np.sort(a)

array([[[ 1,  3,  8, 10, 15],
        [ 1,  4,  9, 13, 50],
        [ 4,  6,  7, 18, 25]]])

In [47]:
b=np.array([[[5,6],[2,3]],[[3,4],[5,6]]])
print(b)

[[[5 6]
  [2 3]]

 [[3 4]
  [5 6]]]


In [49]:
b[0][1][1]

3

In [50]:
b.shape

(2, 2, 2)

In [51]:
b.ndim

3

In [63]:
b=np.array([[[5,6,4],[1,2,3],[2,3,4]],[[3,4,4],[5,6,7],[5,6,4]],[[3,5,4],[9,5,4],[5,8,4]]])
print(b)

[[[5 6 4]
  [1 2 3]
  [2 3 4]]

 [[3 4 4]
  [5 6 7]
  [5 6 4]]

 [[3 5 4]
  [9 5 4]
  [5 8 4]]]


In [64]:
b.shape

(3, 3, 3)

# random number genrator using numpy

practical 1

In [78]:
from numpy import random
#seed random number used to genrate same random value 
random.seed(2)
t= random.randint(1,10)
print(t)

9


In [86]:
#genrate float random number
random.seed(2)
x= random.rand()
print(x)

0.43599490214200376


In [94]:
random.randint(20,100, size=(30))

array([28, 31, 21, 63, 89, 79, 83, 27, 99, 37, 57, 77, 51, 54, 62, 68, 56,
       42, 39, 37, 65, 92, 57, 29, 41, 56, 59, 56, 60, 39])

In [100]:
#genrate random array

from numpy import random
x= random.randint(100, size=(3))
print(x)

[82 93 12]


In [101]:
#genrate 2-D array

from numpy import random
x= random.randint(100, size=(3,2,2))
print(x)

[[[92  6]
  [44  5]]

 [[16 69]
  [52 62]]

 [[26 83]
  [25 36]]]


# practical-2 : creating scaler in numpy

In [102]:
#numpy.asscaler()

import numpy as np

in_arr = np.array([7])

print("input array is ", in_arr)

out_scalar = np.asscalar(in_arr)

print("out scalar from input array", out_scalar)


input array is  [7]
out scalar from input array 7


C:\Users\JAYKUM~1\AppData\Local\Temp/ipykernel_2068/519844608.py:9: DeprecationWarning: np.asscalar(a) is deprecated since NumPy v1.16, use a.item() instead
  out_scalar = np.asscalar(in_arr)


# practical-3 : creating vector in numpy

In [1]:
list1 = [1,2,3]

#creating 1-D list vertical

list2 = [[10],
         [20],
         [30]]
print(list1,list2)

[1, 2, 3] [[10], [20], [30]]


In [3]:
list2[0][0]

10

In [4]:
import numpy as np

#CREATING 1-d list 

list1=[1,2,3]

#creating 1-d list vertical

list2 = [[10,1,1],[20,2,3],[30,3,1]]

#creating vector 1

vector1 = np.array(list1)
vector2 = np.array(list2)

print("horizontal vector")
print(vector1)

print("----------")

print("vertical vector")
print(vector2)


horizontal vector
[1 2 3]
----------
vertical vector
[[10  1  1]
 [20  2  3]
 [30  3  1]]


# practical 4 : Creating matrix in numpy

In [5]:
import numpy as np

a=np.matrix('1,2; 3,4')
print("via string input : \n", a,"\n\n")

#array like input

b = np.matrix([[5,6], [3,4]])
print("via array-like input :\n",b)

via string input : 
 [[1 2]
 [3 4]] 


via array-like input :
 [[5 6]
 [3 4]]


In [6]:
a*b

matrix([[11, 14],
        [27, 34]])

In [8]:
b.ndim

2

In [9]:
b.shape

(2, 2)

In [10]:
# dot product of array

A =np.array([[1,2], [3,4]])
B =np.array([[5,6], [7,8]])
print(A)
print(B)
print(A.dot(B))

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[19 22]
 [43 50]]


In [11]:
print(a)
print(b)

[[1 2]
 [3 4]]
[[5 6]
 [3 4]]


In [3]:
import numpy as np
zero = np.zeros((3,4))
zero

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
once = np.ones((3,3))
once

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
#create constant array

q = np.full((3,3), 7)
q

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [12]:
#identity matrix
w = np.eye(4)
w

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
z=np.array([[1,2,3,4,5],[1,3,4,5,9]])
print(z)

[[1 2 3 4 5]
 [1 3 4 5 9]]


In [19]:
z[1: ,1:3]

array([[3, 4]])

In [20]:
list2 = [[10,1,1],[20,2,3],[30,3,1]]
list2

[[10, 1, 1], [20, 2, 3], [30, 3, 1]]

# array broadcasting 

In [21]:
x=np.array([[1,2],[3,4]])
y=np.array([[4,5],[6,7]])

x,y

(array([[1, 2],
        [3, 4]]),
 array([[4, 5],
        [6, 7]]))

In [22]:
#addition of array

print(x+y)
print(np.add(x,y))

[[ 5  7]
 [ 9 11]]
[[ 5  7]
 [ 9 11]]


In [23]:
#substraction pf array
print(x-y)
print(np.subtract(x,y))

[[-3 -3]
 [-3 -3]]
[[-3 -3]
 [-3 -3]]
